export const countryOptions = [
  { key: 'af', value: 'af', label: 'Afghanistan' },
  { key: 'ax', value: 'ax', label: 'Aland Islands' },
  { key: 'al', value: 'al', label: 'Albania' },
  { key: 'dz', value: 'dz', label: 'Algeria' },
  { key: 'as', value: 'as', label: 'American Samoa' },
  { key: 'ad', value: 'ad', label: 'Andorra' },
  { key: 'ao', value: 'ao', label: 'Angola' },
  { key: 'ai', value: 'ai', label: 'Anguilla' },
  { key: 'ag', value: 'ag', label: 'Antigua' },
  { key: 'ar', value: 'ar', label: 'Argentina' },
  { key: 'am', value: 'am', label: 'Armenia' },
  { key: 'aw', value: 'aw', label: 'Aruba' },
  { key: 'au', value: 'au', label: 'Australia' },
  { key: 'at', value: 'at', label: 'Austria' },
  { key: 'az', value: 'az', label: 'Azerbaijan' },
  { key: 'bs', value: 'bs', label: 'Bahamas' },
  { key: 'bh', value: 'bh', label: 'Bahrain' },
  { key: 'bd', value: 'bd', label: 'Bangladesh' },
  { key: 'bb', value: 'bb', label: 'Barbados' },
  { key: 'by', value: 'by', label: 'Belarus' },
  { key: 'be', value: 'be', label: 'Belgium' },
  { key: 'bz', value: 'bz', label: 'Belize' },
  { key: 'bj', value: 'bj', label: 'Benin' },
  { key: 'bm', value: 'bm', label: 'Bermuda' },
  { key: 'bt', value: 'bt', label: 'Bhutan' },
  { key: 'bo', value: 'bo', label: 'Bolivia' },
  { key: 'ba', value: 'ba', label: 'Bosnia' },
  { key: 'bw', value: 'bw', label: 'Botswana' },
  { key: 'bv', value: 'bv', label: 'Bouvet Island' },
  { key: 'br', value: 'br', label: 'Brazil' },
  { key: 'vg', value: 'vg', label: 'British Virgin Islands' },
  { key: 'bn', value: 'bn', label: 'Brunei' },
  { key: 'bg', value: 'bg', label: 'Bulgaria' },
  { key: 'bf', value: 'bf', label: 'Burkina Faso' },
  { key: 'bi', value: 'bi', label: 'Burundi' },
  { key: 'tc', value: 'tc', label: 'Caicos Islands' },
  { key: 'kh', value: 'kh', label: 'Cambodia' },
  { key: 'cm', value: 'cm', label: 'Cameroon' },
  { key: 'ca', value: 'ca', label: 'Canada' },
  { key: 'cv', value: 'cv', label: 'Cape Verde' },
  { key: 'ky', value: 'ky', label: 'Cayman Islands' },
  { key: 'cf', value: 'cf', label: 'Central African Republic' },
  { key: 'td', value: 'td', label: 'Chad' },
  { key: 'cl', value: 'cl', label: 'Chile' },
  { key: 'cn', value: 'cn', label: 'China' },
  { key: 'cx', value: 'cx', label: 'Christmas Island' },
  { key: 'cc', value: 'cc', label: 'Cocos Islands' },
  { key: 'co', value: 'co', label: 'Colombia' },
  { key: 'km', value: 'km', label: 'Comoros' },
  { key: 'cg', value: 'cg', label: 'Congo Brazzaville' },
  { key: 'cd', value: 'cd', label: 'Congo' },
  { key: 'ck', value: 'ck', label: 'Cook Islands' },
  { key: 'cr', value: 'cr', label: 'Costa Rica' },
  { key: 'ci', value: 'ci', label: 'Cote Divoire' },
  { key: 'hr', value: 'hr', label: 'Croatia' },
  { key: 'cu', value: 'cu', label: 'Cuba' },
  { key: 'cy', value: 'cy', label: 'Cyprus' },
  { key: 'cz', value: 'cz', label: 'Czech Republic' },
  { key: 'dk', value: 'dk', label: 'Denmark' },
  { key: 'dj', value: 'dj', label: 'Djibouti' },
  { key: 'dm', value: 'dm', label: 'Dominica' },
  { key: 'do', value: 'do', label: 'Dominican Republic' },
  { key: 'ec', value: 'ec', label: 'Ecuador' },
  { key: 'eg', value: 'eg', label: 'Egypt' },
  { key: 'sv', value: 'sv', label: 'El Salvador' },
  { key: 'gb', value: 'gb', label: 'England' },
  { key: 'gq', value: 'gq', label: 'Equatorial Guinea' },
  { key: 'er', value: 'er', label: 'Eritrea' },
  { key: 'ee', value: 'ee', label: 'Estonia' },
  { key: 'et', value: 'et', label: 'Ethiopia' },
  { key: 'eu', value: 'eu', label: 'European Union' },
  { key: 'fk', value: 'fk', label: 'Falkland Islands' },
  { key: 'fo', value: 'fo', label: 'Faroe Islands' },
  { key: 'fj', value: 'fj', label: 'Fiji' },
  { key: 'fi', value: 'fi', label: 'Finland' },
  { key: 'fr', value: 'fr', label: 'France' },
  { key: 'gf', value: 'gf', label: 'French Guiana' },
  { key: 'pf', value: 'pf', label: 'French Polynesia' },
  { key: 'tf', value: 'tf', label: 'French Territories' },
  { key: 'ga', value: 'ga', label: 'Gabon' },
  { key: 'gm', value: 'gm', label: 'Gambia' },
  { key: 'ge', value: 'ge', label: 'Georgia' },
  { key: 'de', value: 'de', label: 'Germany' },
  { key: 'gh', value: 'gh', label: 'Ghana' },
  { key: 'gi', value: 'gi', label: 'Gibraltar' },
  { key: 'gr', value: 'gr', label: 'Greece' },
  { key: 'gl', value: 'gl', label: 'Greenland' },
  { key: 'gd', value: 'gd', label: 'Grenada' },
  { key: 'gp', value: 'gp', label: 'Guadeloupe' },
  { key: 'gu', value: 'gu', label: 'Guam' },
  { key: 'gt', value: 'gt', label: 'Guatemala' },
  { key: 'gw', value: 'gw', label: 'Guinea-Bissau' },
  { key: 'gn', value: 'gn', label: 'Guinea' },
  { key: 'gy', value: 'gy', label: 'Guyana' },
  { key: 'ht', value: 'ht', label: 'Haiti' },
  { key: 'hm', value: 'hm', label: 'Heard Island' },
  { key: 'hn', value: 'hn', label: 'Honduras' },
  { key: 'hk', value: 'hk', label: 'Hong Kong' },
  { key: 'hu', value: 'hu', label: 'Hungary' },
  { key: 'is', value: 'is', label: 'Iceland' },
  { key: 'in', value: 'in', label: 'India' },
  { key: 'io', value: 'io', label: 'Indian Ocean Territory' },
  { key: 'id', value: 'id', label: 'Indonesia' },
  { key: 'ir', value: 'ir', label: 'Iran' },
  { key: 'iq', value: 'iq', label: 'Iraq' },
  { key: 'ie', value: 'ie', label: 'Ireland' },
  { key: 'il', value: 'il', label: 'Israel' },
  { key: 'it', value: 'it', label: 'Italy' },
  { key: 'jm', value: 'jm', label: 'Jamaica' },
  { key: 'jp', value: 'jp', label: 'Japan' },
  { key: 'jo', value: 'jo', label: 'Jordan' },
  { key: 'kz', value: 'kz', label: 'Kazakhstan' },
  { key: 'ke', value: 'ke', label: 'Kenya' },
  { key: 'ki', value: 'ki', label: 'Kiribati' },
  { key: 'kw', value: 'kw', label: 'Kuwait' },
  { key: 'kg', value: 'kg', label: 'Kyrgyzstan' },
  { key: 'la', value: 'la', label: 'Laos' },
  { key: 'lv', value: 'lv', label: 'Latvia' },
  { key: 'lb', value: 'lb', label: 'Lebanon' },
  { key: 'ls', value: 'ls', label: 'Lesotho' },
  { key: 'lr', value: 'lr', label: 'Liberia' },
  { key: 'ly', value: 'ly', label: 'Libya' },
  { key: 'li', value: 'li', label: 'Liechtenstein' },
  { key: 'lt', value: 'lt', label: 'Lithuania' },
  { key: 'lu', value: 'lu', label: 'Luxembourg' },
  { key: 'mo', value: 'mo', label: 'Macau' },
  { key: 'mk', value: 'mk', label: 'Macedonia' },
  { key: 'mg', value: 'mg', label: 'Madagascar' },
  { key: 'mw', value: 'mw', label: 'Malawi' },
  { key: 'my', value: 'my', label: 'Malaysia' },
  { key: 'mv', value: 'mv', label: 'Maldives' },
  { key: 'ml', value: 'ml', label: 'Mali' },
  { key: 'mt', value: 'mt', label: 'Malta' },
  { key: 'mh', value: 'mh', label: 'Marshall Islands' },
  { key: 'mq', value: 'mq', label: 'Martinique' },
  { key: 'mr', value: 'mr', label: 'Mauritania' },
  { key: 'mu', value: 'mu', label: 'Mauritius' },
  { key: 'yt', value: 'yt', label: 'Mayotte' },
  { key: 'mx', value: 'mx', label: 'Mexico' },
  { key: 'fm', value: 'fm', label: 'Micronesia' },
  { key: 'md', value: 'md', label: 'Moldova' },
  { key: 'mc', value: 'mc', label: 'Monaco' },
  { key: 'mn', value: 'mn', label: 'Mongolia' },
  { key: 'me', value: 'me', label: 'Montenegro' },
  { key: 'ms', value: 'ms', label: 'Montserrat' },
  { key: 'ma', value: 'ma', label: 'Morocco' },
  { key: 'mz', value: 'mz', label: 'Mozambique' },
  { key: 'na', value: 'na', label: 'Namibia' },
  { key: 'nr', value: 'nr', label: 'Nauru' },
  { key: 'np', value: 'np', label: 'Nepal' },
  { key: 'an', value: 'an', label: 'Netherlands Antilles' },
  { key: 'nl', value: 'nl', label: 'Netherlands' },
  { key: 'nc', value: 'nc', label: 'New Caledonia' },
  { key: 'pg', value: 'pg', label: 'New Guinea' },
  { key: 'nz', value: 'nz', label: 'New Zealand' },
  { key: 'ni', value: 'ni', label: 'Nicaragua' },
  { key: 'ne', value: 'ne', label: 'Niger' },
  { key: 'ng', value: 'ng', label: 'Nigeria' },
  { key: 'nu', value: 'nu', label: 'Niue' },
  { key: 'nf', value: 'nf', label: 'Norfolk Island' },
  { key: 'kp', value: 'kp', label: 'North Korea' },
  { key: 'mp', value: 'mp', label: 'Northern Mariana Islands' },
  { key: 'no', value: 'no', label: 'Norway' },
  { key: 'om', value: 'om', label: 'Oman' },
  { key: 'pk', value: 'pk', label: 'Pakistan' },
  { key: 'pw', value: 'pw', label: 'Palau' },
  { key: 'ps', value: 'ps', label: 'Palestine' },
  { key: 'pa', value: 'pa', label: 'Panama' },
  { key: 'py', value: 'py', label: 'Paraguay' },
  { key: 'pe', value: 'pe', label: 'Peru' },
  { key: 'ph', value: 'ph', label: 'Philippines' },
  { key: 'pn', value: 'pn', label: 'Pitcairn Islands' },
  { key: 'pl', value: 'pl', label: 'Poland' },
  { key: 'pt', value: 'pt', label: 'Portugal' },
  { key: 'pr', value: 'pr', label: 'Puerto Rico' },
  { key: 'qa', value: 'qa', label: 'Qatar' },
  { key: 're', value: 're', label: 'Reunion' },
  { key: 'ro', value: 'ro', label: 'Romania' },
  { key: 'ru', value: 'ru', label: 'Russia' },
  { key: 'rw', value: 'rw', label: 'Rwanda' },
  { key: 'sh', value: 'sh', label: 'Saint Helena' },
  { key: 'kn', value: 'kn', label: 'Saint Kitts and Nevis' },
  { key: 'lc', value: 'lc', label: 'Saint Lucia' },
  { key: 'pm', value: 'pm', label: 'Saint Pierre' },
  { key: 'vc', value: 'vc', label: 'Saint Vincent' },
  { key: 'ws', value: 'ws', label: 'Samoa' },
  { key: 'sm', value: 'sm', label: 'San Marino' },
  { key: 'gs', value: 'gs', label: 'Sandwich Islands' },
  { key: 'st', value: 'st', label: 'Sao Tome' },
  { key: 'sa', value: 'sa', label: 'Saudi Arabia' },
  { key: 'sn', value: 'sn', label: 'Senegal' },
  { key: 'cs', value: 'cs', label: 'Serbia' },
  { key: 'rs', value: 'rs', label: 'Serbia' },
  { key: 'sc', value: 'sc', label: 'Seychelles' },
  { key: 'sl', value: 'sl', label: 'Sierra Leone' },
  { key: 'sg', value: 'sg', label: 'Singapore' },
  { key: 'sk', value: 'sk', label: 'Slovakia' },
  { key: 'si', value: 'si', label: 'Slovenia' },
  { key: 'sb', value: 'sb', label: 'Solomon Islands' },
  { key: 'so', value: 'so', label: 'Somalia' },
  { key: 'za', value: 'za', label: 'South Africa' },
  { key: 'kr', value: 'kr', label: 'South Korea' },
  { key: 'es', value: 'es', label: 'Spain' },
  { key: 'lk', value: 'lk', label: 'Sri Lanka' },
  { key: 'sd', value: 'sd', label: 'Sudan' },
  { key: 'sr', value: 'sr', label: 'Suriname' },
  { key: 'sj', value: 'sj', label: 'Svalbard' },
  { key: 'sz', value: 'sz', label: 'Swaziland' },
  { key: 'se', value: 'se', label: 'Sweden' },
  { key: 'ch', value: 'ch', label: 'Switzerland' },
  { key: 'sy', value: 'sy', label: 'Syria' },
  { key: 'tw', value: 'tw', label: 'Taiwan' },
  { key: 'tj', value: 'tj', label: 'Tajikistan' },
  { key: 'tz', value: 'tz', label: 'Tanzania' },
  { key: 'th', value: 'th', label: 'Thailand' },
  { key: 'tl', value: 'tl', label: 'Timorleste' },
  { key: 'tg', value: 'tg', label: 'Togo' },
  { key: 'tk', value: 'tk', label: 'Tokelau' },
  { key: 'to', value: 'to', label: 'Tonga' },
  { key: 'tt', value: 'tt', label: 'Trinidad' },
  { key: 'tn', value: 'tn', label: 'Tunisia' },
  { key: 'tr', value: 'tr', label: 'Turkey' },
  { key: 'tm', value: 'tm', label: 'Turkmenistan' },
  { key: 'tv', value: 'tv', label: 'Tuvalu' },
  { key: 'ug', value: 'ug', label: 'Uganda' },
  { key: 'ua', value: 'ua', label: 'Ukraine' },
  { key: 'ae', value: 'ae', label: 'United Arab Emirates' },
  { key: 'us', value: 'us', label: 'United States' },
  { key: 'uy', value: 'uy', label: 'Uruguay' },
  { key: 'um', value: 'um', label: 'Us Minor Islands' },
  { key: 'vi', value: 'vi', label: 'Us Virgin Islands' },
  { key: 'uz', value: 'uz', label: 'Uzbekistan' },
  { key: 'vu', value: 'vu', label: 'Vanuatu' },
  { key: 'va', value: 'va', label: 'Vatican City' },
  { key: 've', value: 've', label: 'Venezuela' },
  { key: 'vn', value: 'vn', label: 'Vietnam' },
  { key: 'wf', value: 'wf', label: 'Wallis and Futuna' },
  { key: 'eh', value: 'eh', label: 'Western Sahara' },
  { key: 'ye', value: 'ye', label: 'Yemen' },
  { key: 'zm', value: 'zm', label: 'Zambia' },
  { key: 'zw', value: 'zw', label: 'Zimbabwe' },
];
